### PR TITLE
Cloglog fix2

### PR DESCRIPTION
**Pull request by kaskr**
TODO: We should add some edge case tests for betabinomial.

### CODE REVIEW

**Comment by mebrooks** [comment]
Thanks for fixing it so fast! I'll look into this over the weekend. Today was a long day already.

**Comment by kaskr** [comment]
I had overlooked some details. Need to work a bit more on this but will have to postpone for now.

**Comment by bbolker** [comment]
OK, thanks.

**Comment by kaskr** [comment]
Should be fixed now. Anyone willing to test?

**Comment by mebrooks** [comment]
Yes, I'll test it now.

**Comment by bbolker** [comment]
Don't forget to see the end of the thread in https://github.com/glmmTMB/glmmTMB/issues/564

**Comment by bbolker** [comment]
I think `grep "_link *=" glmmTMB/src/glmmTMB.cpp` should work (although I'd rather specify {whitespace} than a plain space)

**Comment by mebrooks** [comment]
I tried to do this suggested change, but the results seem even worse (25 extra items instead of 2 extra). I'm not very experienced with `grep`. Is anyone else available to debug this?

**Comment by kaskr** [comment]
Does this fix it?

**Comment by mebrooks** [comment]
That fixed the `enum` error. Thanks!

Now some of the tests are complaining.
```
test-families.R:201: failure: dbetabinom
`ff_GA` not equal to `ff1`.
12/12 mismatches (average diff: 0.311)
[1] -0.06563 - -0.000714 == -0.0649
[2] -0.21324 -  0.001141 == -0.2144
[3] -0.15451 -  0.014498 == -0.1690
[4] -0.21517 - -0.006323 == -0.2089
[5] -0.83080 - -0.017451 == -0.8133
[6] -0.47337 -  0.000815 == -0.4742
[7]  0.00390 -  0.029678 == -0.0258
[8]  0.00984 -  0.152433 == -0.1426
[9]  0.02730 -  0.658201 == -0.6309
...

test-families.R:203: warning: dbetabinom
NA/NaN function evaluation

test-families.R:203: warning: dbetabinom
Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
```

**Pull request merged**
