### PR TITLE
rr covstruct

### PR DESCRIPTION
**Pull request by mmcgillycuddy**
Added a reduced rank covariance structure (similar to factor analytic models); I've been in contact with Ben regarding this. Would be happy to hear comments.

### CODE REVIEW

**Comment by bbolker** [comment]
This is failing because of some rearrangements in the master branch (distribution functions moved to a separate file).  The fix for this is (1) pull upstream into @mmcgillycuddy fork; (2) resolve merge conflicts; (3) re-merge @mmcgillycuddy master into rr_covstruct.  Maeve, if you give me write access to your fork I can do it if you like.

Would be nice to resolve all this before merging (in a pinch we could do it afterward but I'd really rather not).

More generally, as far as "review" goes: I have been looking at this along the way, in general I think it's pretty good, but I haven't looked at it super carefully recently.

@mmcgillycuddy , if you can stand it I think the most useful thing would be if you could write a short `README` file that describes the new features, and especially describes/summarizes the changes to the API and basic structure that you made in order to make everything work ...

**Comment by mmcgillycuddy** [comment]
Hi @bbolker, I think you have write access already? 

Yes, I will get on that tomorrow. Is there somewhere in particular I should save it, or just attach here?

**Comment by mebrooks** [comment]
On a selfish note, it would be helpful for me and another project I'm working on if the documentation said if this can be used to fit joint species distribution models. I forget the details from your ISEC 2020 talk. I realize you're probably writing it up in a manuscript and dissertation, but something brief would be helpful.

**Comment by mmcgillycuddy** [comment]
Hi @bbolker, sorry for the headaches! I have done this on the rr_covstruct branch, and everything should be up to date? Should I update my master branch also? When running check, I get the following error: Fatal error: can't write 308 bytes to section .text of glmmTMB.o: 'file too big'. Any ideas how I can fix this/what's going wrong? 

Hi @mebrooks, yes I can do that!

**Comment by bbolker** [comment]
Yay, passes tests now; I had to update some stored results. Note that stored fits from previous releases *will not* work with this version (because we added new stuff to the internal structures). This frustrates me a bit but I think it's more or less unavoidable.

@mmcgillycuddy  (I don't know if you're automatically getting notified on this thread, I would imagine so):
- I don't know what your test problem is - not a big deal if you can't resolve it, as stuff will get tested on Github Actions when you push anyway (unless you add "[skip ci]" to the end of your commit message)
- some things are still a little bit under-documented (although possibly they were even before you started?)
      - e.g. see `getXReTrms`
      - can you create a document somewhere (maybe as part of the `covstruct` vignette that describes your general strategy for finding starting values etc.? (Is this already documented somewhere in work you/your group has already done on rank-reduced models?)

We don't necessarily have to do everything before we merge, but it would be good to get as much as we can done (the incentive to do stuff will drop off a lot once we've merged)

**Comment by mmcgillycuddy** [comment]
Hi @bbolker, wahoo! Thanks for updating the stored fits; I discovered the issue yesterday but I wasn't sure what was the best way to go about it.  

Yes I automatically get notified.
- `getXReTrms` was outdated, but I will update what I can. 
- I will work on document, for now I've attached a brief summary of changes made/API and the strategy of obtaining starting values 
[readme.pdf](https://github.com/glmmTMB/glmmTMB/files/6119513/readme.pdf).

**Comment by bbolker** [comment]
At a quick glance that looks great.  Unless you want it in a separate vignette for greater visibility it might make sense to add the first two sections to the "covariance structures" vignette (the last part looks more developer-focused, and might not need to be kept after all the bits are appropriately documented internally ...

**Review by bbolker — COMMENTED** [review]
I think this is pretty much ready to go. I would feel a little better if one other person besides me looked at it.  Some *optional* improvements:

- document the format in which the loadings etc. are parameterized/stored internally: how would a user retrieve these if they wanted them?
- maybe suggest how the rank might be chosen (AIC)?
- maybe an example in the vignette going through one or more of the examples in Niku et al? (@mmcgillycuddy , have you run these comparisons yet?)

And some more thoughts:

- improve the print method for the covariance matrices? (how does `gllvm` do it?)  (This is a general thing we need to do better with complex covariance structures)

**Comment by kaskr** [comment]
It seems to be working now, however perhaps it would be possible to make it more in line with the structure of current
https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp

We normally have everything related to covariance structures in the helper function `termwise_nll`
https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L180
and all the bookkeeping of parameters related to covariance structures in the helper function `allterms_nll` 
https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L374

I would therefore have expected the majority of these lines
https://github.com/mmcgillycuddy/glmmTMB/blob/rr_covstruct/glmmTMB/src/glmmTMB.cpp#L478-L521
to go to the helper functions. Any reason why this wasn't done in the first place?

**Comment by bbolker** [comment]
Haven't checked carefully: @mmcgillycuddy can you see how far the restructuring requested by @kaskr can be done? I know there will be at least some components (e.g. new machinery for specifying starting values) that won't fit into the standard template, but most of it should ... ?

**Comment by mmcgillycuddy** [comment]
Hi @kaskr and @bbolker. Yes, I tried adding everything to the helper function of [termwise_nll ](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L180) but at the time I wasn't able to get it to work. I will try again.

**Comment by bbolker** [comment]
ugh, there is a little bit of a rabbit hole about what does and doesn't get evaluated within vignettes ... don't quite know why it's popping up at this point.

**Comment by mmcgillycuddy** [comment]
@bbolker yes, sorry... I forgot about the vignettes data when I merged!

**Comment by bbolker** [comment]
@mmcgillycuddy not necessarily your fault. Fingers crossed for the last tweak ...

**Comment by mmcgillycuddy** [comment]
Hi @kaskr, I cannot add rr_covstruct to the helper function of termwise_nll as others have been; sigma is not invertible. Or do you have any ideas on how it can be done?

**Comment by kaskr** [comment]
@mmcgillycuddy 
u is passed by reference, so you can do:

```
ans -= dnorm(u,0,1,log=TRUE); // u ~ N(0,I)
u_sub = u[1:rank]             // The unused part of u becomes dummy
u = Lambda * u_sub            // Now u ~ N(0,Lambda*Lambda')
```

within `termwise_nll`. (Sigma need not be computed...)

This means changing the code to something like:

```cpp
else if (term.blockCode == rr_covstruct){
  // case: reduced rank
  // Keep what you already have here BUT ASSUMING THAT U columns have the full (not reduced) size:
  for(int i = 0; i < term.blockReps; i++){
    ans -= dnorm(vector<Type>(U.col(i)), Type(0), 1, true).sum();
    if (do_simulate) {
      U.col(i) = rnorm(U.rows(), Type(0), Type(1));
    }
  }
  // We want to keep `term_t` as simple as possible so better avoid passing `blockRank` (I'm guessing it can be computed from the number of parameters of the term?):
  int rank = ...; // Some function of theta.size() and U.col size?
  matrix<Type> Lambda = ...; // Compute Lambda from theta.
  // NOTE: kronecker product expansion can be avoided. Just multiply each replicate in a loop.
  for(int i = 0; i < term.blockReps; i++){
    vector<Type> usub = U.col(i).segment(0, rank);
    U.col(i) = Lambda * U.col(i);
  }
}
```

I'm spotting a few more things that should be fixed:

- Something is not right if you have to pass `DATA_INTEGER(dorr)`...
- And all the upointer, unewpointer, tpointer stuff should not be reinvented...

Thanks!

**Comment by mmcgillycuddy** [comment]
@kaskr, I have changed the structure of rr to be more in line with previous versions, and I removed blockRank. Is there any other issues?

**Comment by kaskr** [comment]
@mmcgillycuddy 
Looks good!
I notice other covstructs fill the slots `term.corr` and `term.sd` as for example here:

https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L277-L288

This is (as far as I recall) used by the print method and may need to implemented (@bbolker ?). It should be easy to add for the rr struct as well, perhaps :

```cpp
if(isDouble<Type>::value) {
  term.corr = Lambda * Lambda.transpose();
  term.sd = term.corr.diagonal().array().sqrt();
  term.corr.array() /= term.sd * term.sd.transpose();
}
```

**Comment by mmcgillycuddy** [comment]
Hi, @kaskr great! Ah yes, I had changed the print function for the old method but makes more sense now to have it there. I have added this in and removed my modification in VarCorr.

**Comment by kaskr** [comment]
The [diff](https://github.com/glmmTMB/glmmTMB/pull/670/files) looks much cleaner now. I'm OK with it as is but @mmcgillycuddy  could you go over the diff one more time to see if there's something obvious to fix (I see e.g. `over-overparameterization`...) before we merge?

**Comment by mmcgillycuddy** [comment]
@kaskr ah yes, I've gone through it and fixed a few things.

**Comment by mebrooks** [comment]
The `covstruct` vignette is helpful; thanks @mmcgillycuddy. I'm just trying this out and want to make sure I understand before I apply it to my own data (and students' data). I did a test using the `Salamanders` dataset. The 8 levels of `spp` aren't all different species; `sppEC-A` and `sppEC-L` are adults and larvae of the same species. If I understand the covariance matrix below, I think it says that those two levels of `spp` have 0.78 correlation which makes sense biologically. The highest correlation 0.92 is for `sppGP` and `sppDM` if I understand the results. That describes their concurrence after controlling for the effect of mining. Is that right?

```
> library(glmmTMB)
> library(bbmle)
> 
> m2 <- glmmTMB(count~mined* spp + rr(spp+0|site, d=2), Salamanders, family=nbinom2)
> m3 <- glmmTMB(count~mined* spp + rr(spp+0|site, d=3), Salamanders, family=nbinom2)
> m4 <- glmmTMB(count~mined* spp + rr(spp+0|site, d=4), Salamanders, family=nbinom2)
> 
> AICctab(m2, m3, m4)
   dAICc df
m3  0.0  33
m2  7.6  28
m4  7.6  37
> 
> m3
Formula:          count ~ mined * spp + rr(spp + 0 | site, d = 3)
Data: Salamanders
      AIC       BIC    logLik  df.resid 
1644.8724 1792.3065 -789.4362       611 
Random-effects (co)variances:

Conditional model:
 Groups Name     Std.Dev. Corr                                
 site   sppGP    0.7458                                       
        sppPR    2.0744    0.54                               
        sppDM    0.8809    0.92  0.28                         
        sppEC-A  0.5823    0.68  0.50  0.78                   
        sppEC-L  1.0402    0.15  0.21  0.37  0.83             
        sppDES-L 1.0617    0.74  0.85  0.43  0.29 -0.20       
        sppDF    0.7795   -0.24  0.64 -0.37  0.22  0.44  0.17 

Number of obs: 644 / Conditional model: site, 23

Dispersion parameter for nbinom2 family (): 1.73 

Fixed Effects:

Conditional model:
     (Intercept)           minedno             sppPR             sppDM           sppEC-A           sppEC-L          sppDES-L  
         -3.5419            4.2166           -1.2031            2.1742            0.9094            1.6329            2.1387  
           sppDF     minedno:sppPR     minedno:sppDM   minedno:sppEC-A   minedno:sppEC-L  minedno:sppDES-L     minedno:sppDF  
          2.5897           -0.9659           -2.1623           -1.7222           -1.2987           -1.5956           -2.8496  

```

**Comment by mmcgillycuddy** [comment]
Hi @mebrooks, sorry for the delay! Yes I think you've got it, except the correlation between `sppEC-A `and `sppEC-L` is `0.83`. I find it is hard to match which correlation corresponds to which pair of species, but it's much easier to read from the code below. 
```
> round( attr((VarCorr(m3)$cond$site), "correlation"), 2)
         sppGP sppPR sppDM sppEC-A sppEC-L sppDES-L sppDF
sppGP     1.00  0.54  0.92    0.68    0.15     0.74 -0.24
sppPR     0.54  1.00  0.28    0.50    0.21     0.85  0.64
sppDM     0.92  0.28  1.00    0.78    0.37     0.43 -0.37
sppEC-A   0.68  0.50  0.78    1.00    0.83     0.29  0.22
sppEC-L   0.15  0.21  0.37    0.83    1.00    -0.20  0.44
sppDES-L  0.74  0.85  0.43    0.29   -0.20     1.00  0.17
sppDF    -0.24  0.64 -0.37    0.22    0.44     0.17  1.00
```

**Comment by mebrooks** [comment]
Thanks for the code for extracting this. It's very helpful. I'm going to show this to some PhD students next week.

**Pull request merged**
