### PR TITLE
add Bell distributions

### PR DESCRIPTION
**Pull request by bbolker**
This still needs testing, and tests (i.e. both a human looking to see if comparisons with e.g. `bellreg::bellreg()` make sense, and adding `testthat` tests), but I think it more or less works.

Based on initial code provided by @haticeakdur <https://github.com/haticeakdur> and modified here: https://github.com/bbolker/bell_TMB (some testing machinery from https://github.com/bbolker/bell_TMB/blob/main/bell_test2.R maybe worth pulling in)

This does add a Suggests: dependency on `gsl` <strike>(may have to be upgraded to `Imports:`, haven't tried R CMD check yet)</strike>, but that package is at least stable and widely used.

### CODE REVIEW

**Comment by bbolker** [comment]
To test, try **exactly** this code:  (no other `devtools::load_all()`, etc.), from a clean R session:

```r
library(remotes)
remotes::install_github("glmmTMB/glmmTMB/glmmTMB", ref = "bell")
library(glmmTMB)
dd <- data.frame(x = 1:5)
fit1 <- glmmTMB(x ~ 1, data = dd, family = bell())
## mean value
c0 <- fixef(fit1)$cond[1]
exp(c0)*exp(exp(c0))  ## 3
predict(fit1)
```

If it doesn't work, please report all warnings/errors and the results of `sessionInfo()`.

**Comment by haticeakdur** [comment]
Dear Dr. Bolker
I run the code above in clean R environment but it produces the error below: 
> fit1 <- glmmTMB(x ~ 1, data = dd, family = bell())
Error in bell() : argument "n" is missing, with no default

Thank you

**Comment by bbolker** [comment]
I suspect you have another package loaded that is masking the `bell()` family function. It might make sense to rename `bell()` to `bell_family()` in the code. In the meantime, try

```r
fit1 <- glmmTMB(x ~ 1, data = dd, family = glmmTMB::bell())
```

and see how it goes.

**Comment by haticeakdur** [comment]
I've run the code:
> fit1 <- glmmTMB(x ~ 1, data = dd, family = glmmTMB::bell()) 
Error:
Loading required namespace: gsl Failed with error:  ‘there is no package called ‘gsl’’ Error in glmmTMB::bell() :    the gsl package must be installed in order to use the Bell family

Thank you!

**Comment by bbolker** [comment]
Please installl the `gsl` package as suggested ...

**Comment by haticeakdur** [comment]
Dear Dr. Bolker,

I've run these code or a well known count dataset (leprosy dataset). 

GLMMadaptive code:
##user defined function for GLMMadaptive package##
my_bell<- function (link = "log") {
stats <- make.link(link)
log_dens_mu <- function (y, eta, mu_fun, phis, eta_zi) {
         # the log density function
         # you link log(mu) to covariates
         mu <- as.matrix(mu_fun(eta))
                comp1 <- y*log(W(mu))
         comp2 <- -exp(W(mu))
                  out <- comp1 + comp2
         attr(out, "mu_y") <- mu
         out
     }

log_dens <- function (y, eta, mu_fun, phis, eta_zi){
# the derivative of the log density w.r.t. mu
mu <- as.matrix(mu_fun(eta))
         theta <- W(mu)
         
         comp1 <- -exp(theta)
         comp3 <- log(theta)*(y)
    
         out <- (comp1 + comp3)
 attr(out, "mu_y") <- mu
         out
}
score_eta_fun <- function (y, mu, phis, eta_zi) {
# the derivative of the log density w.r.t. mu
mu <- as.matrix(mu)
         theta <- W(mu)
         # the derivative of the log density w.r.t. theta
         comp1 <-  -exp(theta)
         comp3 <- (1/theta)*(y)
         # the derivative of theta w.r.t mu
         tht_mu <- W(mu)/(mu*W(mu)+mu)
         # the derivative of mu w.r.t. eta log link
         mu_eta <- mu
         (comp1 + comp3) * tht_mu * mu_eta

}

score_phis_fun <- function (y, mu, phis, eta_zi) {
# the derivative of the log density w.r.t. phis

}
 structure(list(family = "user bell", link = stats$name, linkfun = stats$linkfun,
                   linkinv = stats$linkinv, 
                   log_dens = log_dens, 
                   score_eta_fun = score_eta_fun),
              class = "family")
}
######################


library(GLMMadaptive)
#set.seed(1234)
library(MASS)
library(lme4)
library(xlsx)
################
## Leprosy dataset

leprosy <- read.dta("leprosy.dta")

## To long format
leprosy.long <- reshape(data= leprosy,
                 varying= paste0("y",1:2),
                  ##v.names   = "",
                 timevar= "time",
                 idvar= "id",
                 direction= "long",
                 sep= ""
                 )
## Change time 1, 2 to 0, 1
leprosy.long$time <- leprosy.long$time - 1
## Placebo as control
leprosy.long$drug <- relevel(leprosy.long$drug, ref = "Drug C")
## Order by id and then time
leprosy.long <- leprosy.long[with(leprosy.long, order(id, time)),]

fm1 <- mixed_model(fixed = y ~ time*drug, random = ~ 1| id,data=leprosy.long,
family =my_bell(),max_coef_value = 50,initial_values = list("betas" = poisson()))# Laplace approximation
summary(fm1)
#####glmmTMB code
glmm.model <- glmmTMB(y ~  time*drug+ (1|id),
                        data = leprosy.long,
                        na.action = na.omit,
                        family = glmmTMB::bell())


summary(glmm.model)


#####results###

Call:
mixed_model(fixed = y ~ time * drug, random = ~1 | id, data = leprosy.long, 
    family = my_bell(), initial_values = list(betas = poisson()), 
    max_coef_value = 50)

Data Descriptives:
Number of Observations: 60
Number of Groups: 30 

Model:
 family: user bell
 link: log 

Fit statistics:
   log.Lik      AIC      BIC
 -17.28096 48.56193 58.37031

Random effects covariance matrix:
               StdDev
(Intercept) 0.3936266

Fixed effects:
                Estimate Std.Err z-value p-value
(Intercept)       2.5121  0.1962 12.8050 < 1e-04
time             -0.0633  0.2150 -0.2945 0.76838
drugDrug A       -0.3542  0.2895 -1.2236 0.22109
drugDrug B       -0.2932  0.2871 -1.0214 0.30707
time:drugDrug A  -0.5230  0.3483 -1.5016 0.13320
time:drugDrug B  -0.4667  0.3401 -1.3723 0.16998

Integration:
method: adaptive Gauss-Hermite quadrature rule
quadrature points: 11

Optimization:
method: hybrid EM and quasi-Newton
converged: TRUE 
###
> summary(glmm.model)
 Family: bell  ( lambertW )
Formula:          y ~ time * drug + (1 | id)
Data: leprosy.long

     AIC      BIC   logLik deviance df.resid 
      NA       NA       NA       NA       53 

Random effects:

Conditional model:
 Groups Name        Variance Std.Dev.
 id     (Intercept) 0.7024   0.8381  
Number of obs: 60, groups:  id, 30

Conditional model:
                Estimate Std. Error z value Pr(>|z|)  
(Intercept)      0.65538    0.26939   2.433    0.015 *
time             0.00650    0.07943   0.082    0.935  
drugDrug A       0.18443    0.31237   0.590    0.555  
drugDrug B       0.19509    0.31960   0.610    0.542  
time:drugDrug A -0.05431    0.13558  -0.401    0.689  
time:drugDrug B -0.04635    0.12974  -0.357    0.721  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> 

----
Can you check the result of these two models please
Thank you
[leprosy.txt](https://github.com/user-attachments/files/16949704/leprosy.txt)
[leprosy.xlsx](https://github.com/user-attachments/files/16949708/leprosy.xlsx)

Thank you

**Comment by bbolker** [comment]
I will take a look at this. At the moment I'm having a little trouble making sure the parameters are even on the same scales (i.e. that we're really using the same link function ...)

**Comment by bbolker** [comment]
I had two non-trivial problems to fix

- I was using `expm1` in the C++ code, which isn't handled properly by TMB
- I wasn't handling the link function machinery properly.

With the current version of the code, `glmmTMB` and `GLMMadaptive` fitted coefficients agree with a mean relative difference of about 1.6e-4.

Can you test some more please?

**Comment by haticeakdur** [comment]
Dear Dr. Bolker
Thank you very much for your serious effort to add bell family to glmmTMB.
I am going to re-design the simulation study using glmmTMB (carried out previously with GLMMadaptive package). My simulation design had some problems with the GLMMapative package as mentioned before.
The leprosy dataset is very old:
"Count data from a placebo-controlled clinical trial of 30 patients with leprosy at the Eversley Childs Sanitarium in the Philippines (Snedecor and Cochran, 1967)."-Snedecor, G.W. and Cochran, W.G. (1967). Statistical Methods, 6th ed. Ames,
IA: Iowa State Press.
I obtained the data from this link :https://www.sfu.ca/sasdoc/sashtml/stat/chap30/sect53.htm
This data was analyzed also in the book "Applied Longitudinal Analysis" by Fitzmaurice in the page 389-394
I am going to let you know how my simulation goes. I hope it would be better.
Best!

**Comment by bbolker** [comment]
For what it's worth, `glmmTMB` seems to give reasonable answers on the data that you provided earlier (the "accident" data set).

```r
families <- c("poisson", "nbinom2", "nbinom1", "bell")
fits <-lapply(families,
              function(f) {
                  glmmTMB(response ~ time+length + (1| subject),
                          data=simdata, family = f)
              })
names(fits) <- families
bbmle::AICtab(fits)
```

The Bell distribution doesn't fit as well as the negative binomial options (but way better than Poisson):

```
         dAIC  df
nbinom1   0.0 5 
nbinom2   1.7 5 
bell     12.4 4 
poisson 300.0 4 
```

```r
pp <- cbind(response = simdata$response,
            sapply(fits, predict, type = "response"))
pairs(pp, gap = 0,
      panel = function(x, y, ...) {
          points(x, y, ...)
          abline(a=0, b=1, col = "red")
        })
```

bell_pairs

**Comment by bbolker** [comment]
To do (possibly) before merging:

- add "fabrics" and leprosy data sets, with refs/sources and descriptions

- https://support.sas.com/documentation/onlinedoc/stat/141/glm.pdf; Mills library HA 29 .S67S;  Snedecor, George W., and William G. Cochran. Statistical Methods. 6th ed. Ames, Iowa State University Press, 1967 (table 14.2.1, p. 422)
- (fabric data) Hinde, John. “Compound Poisson Regression Models.” In GLIM 82: Proceedings of the International Conference on Generalised Linear Models, edited by Robert Gilchrist, 14:109–21. Lecture Notes in Statistics. New York, NY: Springer New York, 1982. https://doi.org/10.1007/978-1-4612-5771-4_11.

**Comment by haticeakdur** [comment]
Woowww!! It is very good news! I was also thinking to check the accident dataset.
You are the best!
Thank you again
Best!

**Comment by haticeakdur** [comment]
Hi
Have you included changes to the package in the bell family?
I've tried the code but it fails :(

remotes::install_github("glmmTMB/glmmTMB/glmmTMB", ref = "bell")
Downloading GitHub repo glmmTMB/glmmTMB@bell
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/glmmTMB/glmmTMB/tarball/bell' failed

**Comment by bbolker** [comment]
I think but am not sure that this just a network issue.  If possible, clone the repository, check out the `bell` branch, and install from there ... ???

**Comment by haticeakdur** [comment]
I'll try that. Thank you!

**Comment by haticeakdur** [comment]
Hello,

Without experience, I've cloned the bell branch from the github repo. However, there is an error: (model summary looks OK)
fit2<-glmmTMB(response ~ time+length + (1| subject),
                        data=simdata, family = glmmTMB::bell())
bbmle::AICtab(fit2)

Error in UseMethod("logLik") :    no applicable method for 'logLik' applied to an object of class "list"

##
glmmTMB(response ~ time+length + (1| subject),               data=simdata, family = glmmTMB::bell())
Formula:          response ~ time + length + (1 | subject)
Data: simdata
      AIC       BIC    logLik  df.resid 
1001.5170 1012.6669 -496.7585       116 
Random-effects (co)variances:

Conditional model:
 Groups  Name        Std.Dev.
 subject (Intercept) 0.5975  

Number of obs: 120 / Conditional model: subject, 24

Fixed Effects:

Conditional model:
(Intercept)         time       length  
    2.65569     -0.03021      0.22547

**Comment by haticeakdur** [comment]
Which address exactly I should clone?
Is it true?
# Clone the repository
system("git clone https://github.com/glmmTMB/glmmTMB.git")
Thank you!

**Comment by bbolker** [comment]
This appears to be an issue/bug with `bbmle::AICtab()` when you give it only a single fitted object (normally you wouldn't bother using `AICtab()` for a single fit, you would just use `AIC`.

For example:

```r
library(glmmTMB)
data("faults", package = "bellreg")
fit2<-glmmTMB::glmmTMB(nf ~ lroll, data = faults, family = glmmTMB::bell())
try(bbmle::AICtab(fit2))  ## error
fit3 <- fit2
bbmle::AICtab(fit2, fit3)
```

If the model fits OK and the summary is OK, I think you've done all the cloning etc. right.

If you have cloned the repo and want to get onto the "bell" branch, do `git checkout bell` from the command line (there's probably a way to do it in RStudio as well)

**Comment by haticeakdur** [comment]
It seems the cloning is not done properly...I am not sure...
fit2<-glmmTMB(response ~ time+length + (1| subject),
                        data=simdata, family = glmmTMB::bell())
fit1<-glmmTMB(response ~ time+length + (1| subject),
              data=simdata, family = poisson)
> bbmle::AICtab(fit1,fit2)
     dAIC   df
fit2    0.0 2 
fit1 1107.2 4 

I hope I can make it work :(

**Comment by bbolker** [comment]
Try the `remotes::install_github("glmmTMB/glmmTMB/glmmTMB", ref = "bell")` installation method again? (I think there may have been some issues with github a few days ago). 

(I agree that the `df` output is surprising!)

**Comment by haticeakdur** [comment]
None of them works out ::(
 data("faults", package = "bellreg")
> fit2<-glmmTMB::glmmTMB(nf ~ lroll, data = faults, family = glmmTMB::bell())
There were 12 warnings (use warnings() to see them)
> try(bbmle::AICtab(fit2))  ## error
Error in UseMethod("logLik") : 
  no applicable method for 'logLik' applied to an object of class "list"
> fit3 <- fit2
> bbmle::AICtab(fit2, fit3)
     dAIC df
fit2 0    2 
fit3 0    2

**Comment by bbolker** [comment]
The results you just posted are all correct, and all exactly as expected.  These results you posted earlier look fishy:

```
 bbmle::AICtab(fit1,fit2)
     dAIC   df
fit2    0.0 2 
fit1 1107.2 4 
```

because both models should have 4 parameters (not 2 for fit2).  Otherwise as expected -- I would expect `fit2` (Bell distribution) to have a much better (lower) AIC than `fit1` (Poisson). Possibly a cut-and-paste error?  If the `df` values were the same this would be consistent with the example I posted above ([here](https://github.com/glmmTMB/glmmTMB/pull/1087#issuecomment-2351768327))

**Comment by bbolker** [comment]
To make this self-contained:

```r
simdata <- data.frame(
  response = c(
    11, 33, 25, 23, 6, 41, 63, 91, 77, 29, 5, 35, 44, 21, 13, 44, 79, 91, 88, 33,
    5, 3, 4, 4, 0, 8, 15, 26, 13, 7, 34, 63, 81, 67, 23, 17, 16, 24, 24, 4, 16,
    24, 30, 30, 13, 13, 13, 15, 17, 9, 7, 15, 20, 19, 8, 15, 24, 39, 32, 7, 2, 3,
    27, 24, 7, 22, 23, 38, 22, 11, 38, 48, 60, 53, 24, 4, 6, 12, 9, 3, 19, 30, 37,
    48, 22, 15, 11, 16, 21, 28, 20, 30, 33, 28, 9, 13, 14, 13, 17, 9, 24, 58, 40,
    36, 5, 80, 108, 114, 113, 86, 86, 89, 109, 90, 49, 60, 61, 87, 86, 29
  ),
  time = rep(1:5, 24),
  subject = rep(1:24, each = 5L),
  length = rep(
    c(
      1.2, 2.6, 2.4, 5.5, 0.5, 1.3, 2.6, 2.1, 1.7, 1.1, 2.7, 2.6, 1.4, 7.9, 2, 6.1,
      1.5, 2.6, 1.1, 4.1, 8, 4.8
    ),
    rep(c(5L, 10L, 5L, 10L, 5L), c(12L, 1L, 1L, 1L, 7L))
  )
)
library(glmmTMB)
fit2<-glmmTMB(response ~ time+length + (1| subject),
                        data=simdata, family = glmmTMB::bell())
fit1<-glmmTMB(response ~ time+length + (1| subject),
              data=simdata, family = poisson)
bbmle::AICtab(fit1,fit2)
```

I get this:

```
    dAIC  df
fit2   0.0 4 
fit1 287.6 4 
```

**Comment by haticeakdur** [comment]
OK. Thank you very much! It is a relief!

**Pull request merged**
