### PR TITLE
Add beta family simulate #357

### PR DESCRIPTION
**Pull request by kaskr**

### CODE REVIEW

**Comment by bbolker** [comment]
that was tough :-)

**Comment by bbolker** [comment]
failed test on r-devel because vignette build took >10 minutes.  We could ignore this for now, but we probably have to fuss with travis settings (either add `travis_wait` specs appropriately, or skip vignette building in tests ...)

**Comment by bbolker** [comment]
should we try to fix the travis issues before or after merging?

**Comment by mebrooks** [comment]
I got an email from CRAN this morning pointing out the same problem: one of the vignettes is building too slowly. The deadline to fix it is July 2nd. I don't have time to look at it at this moment, but will tomorrow...unless someone else gets to it first.

**Comment by mebrooks** [comment]
I've been discussing this with Koen and the other DTU developers. @koenvanbenthem wrote code to get the timing of the vignettes. 
On my computer they are:
```
                    user.self sys.self elapsed
covstruct.rmd         98.386   9.048 107.590 
glmmTMB.Rnw           20.422   0.159  20.743
mcmc.rmd               1.907   0.177   2.208
miscEx.rmd             0.460   0.007   0.468
sim.rmd                2.610   0.045   2.721
troubleshooting.rmd   34.097   0.205  34.470
```
and they are similar on Koen's computer 
```
                    user.self sys.self elapsed
covstruct.rmd         105.826    1.584 108.609
glmmTMB.Rnw            13.129    0.060  13.907
mcmc.rmd                2.727    0.008   3.017
miscEx.rmd              0.381    0.000   0.381
sim.rmd                 2.444    0.000   2.519
troubleshooting.rmd    30.666    0.016  30.735
```

[Here's](https://cran.r-project.org/web/checks/check_results_glmmTMB.html) the latest cran check. The cran maintainer said it shows "very long run times for rebuilding the vignette outputs, often hitting the timeouts used for the check runs".

Is the criteria the *total* time to run all the vignettes? If so, it seems that we should probably keep the essential information in the vignettes and move some of the other information (possibly entire vignettes) to Github. At DTU, we were discussing this solution because, while `covstruct.rmd` is the slowest, it also contains lots of essential information.

Another solution is to avoid running some of the code by storing more objects (e.g. I could probably just use plain text in `troubleshooting.rmd` instead of running the models that don't converge).

**Comment by mebrooks** [comment]
Also, since cran requests that we fix this by July 2, this is an opportunity to get in whatever fixes we want in the next version. Open for discussion...

**Comment by mebrooks** [comment]
To answer @bbolker 's earlier question, I think we can merge and then deal with the vignettes in separate pull requests.

**Comment by kaskr** [comment]
It's not just the vignettes. Our tests also have to be reduced:

```
Check: tests
Result: ERROR
     Running ‘AAAtest-all.R’ [10m/12m]
    Running the tests in ‘tests/AAAtest-all.R’ failed.
```

Judging from this:

```
checking re-building of vignette outputs ... [10m/12m] WARNING
Error in re-building vignettes:
  ...
Killed
```

I'm guessing the time limit for tests and vignettes are the same - and we should keep in mind that the CRAN machines aren't the fastest...

**Comment by mebrooks** [comment]
Yep. It looks like CRAN's machines are more than 3.6 times slower than Koen and my computers. We don't know how far it got in the vignettes before killing them, presumably after 10 minutes, but what does the 12m refer to?

**Comment by mebrooks** [comment]
vignette speed discussion moved to #364

**Pull request merged**
