### PR TITLE
Evaluating negative log-likelihood in parallel if OpenMP threads are available

### PR DESCRIPTION
**Pull request by sadatnfs**
- Initiating negative log-likelihood as a parallel region, getting the max number of OpenMP threads using a function from `omp.h`.
- Adding OpenMP flag for Makevars CPP/CXXFLAGS so that the model is compiled with the OpenMP flags (if available in R's Makeconf)

### CODE REVIEW

**Comment by sadatnfs** [comment]
Actually, it turns out that not setting any threads actually segfault the model from the TMB side. Will fix it.

**Comment by bbolker** [comment]
can you confirm that this is now OK as far as you know? Does it need documentation somewhere?

**Comment by sadatnfs** [comment]
actually @bbolker , there is a lingering issue where if we don't explicitly declare OpenMP (even for a single thread), the model segfaults out.

**Comment by sadatnfs** [comment]
I'll look into this more over the weekend on whether I can automate some of this. I have a C code which can set OpenMP threads from within an R process, so that might be something worth embedding for multithreading.

**Comment by sadatnfs** [comment]
Actually... I didn't even realize that TMB itself has an `openmp` C function to go in and grab/set OpenMP threads. What do you think having this as an on-load call in glmmTMB? We could have it always be set to 1 thread whenever the user loads the library, but they have the freedom to multi-thread their model with `TMB::openmp(num_of_threads)`.

**Comment by bbolker** [comment]
I don't have strong feelings/opinions about best practices. Putting in `control` seems to make the most sense to me. @kaskr ? @mmaechler ? @mebrooks ?

**Comment by sadatnfs** [comment]
Just added it on to `glmmTMBcontrol` with documentation. Would you want any tests on this on the Travis side, or an R script benchmarking run times on a simple model with a large number of observations?

**Comment by kaskr** [comment]
Some comments and suggestions:

* We want to make sure that single thread models run as fast and memory efficient as before. Comparing `time make test` for the master branch versus the parallel branch will give a first indication.
* Motivating examples where parallelization makes a difference would be nice but probably not as part of the travis setup. FWIW we already have some heavy test examples [here](https://github.com/glmmTMB/glmmTMB/blob/master/misc/problematic/psinger.R).
* Can we expect installation across platforms to be as robust as before? I seem to recall some platforms don't have OpenMP properly configured.
* The `+=` in `Makevars` is a GNU Makefile extension. I expect CRAN will complain.

**Comment by sadatnfs** [comment]
Thanks @kaskr. 

- I can totally add some super simple models so that `make test` can pick those up. Do you know if Travis is configured to be able to do multithreaded tests (as in, how many threads can we safely ask for in our OpenMP tests)?
- Great question on the OpenMP configuration example. Right now the `Makevars` is using the `SHLIB_OPENMP_CXXFLAGS` variable to pick up on the OpenMP flag, so if the user didn't build their R with OpenMP, then this would do nothing. 
Also, I just tested that when I *don't* have the OpenMP variables in my Makefile and have compiled the `glmmTMB.cpp` model, any number of `parallel` threads always default to 1 when running the model, which is great.
- Finally, for the `+=` assignment, I haven't yet found a hack to assign over the `PKG_C*FLAGS` variable in the `Makevars` yet without using `+=`, since all my attempts ended up either not picking up the flag, or a recursive reference error. Hopefully this won't be a problem, since I see that TMB also have `+=` in the `Makevars` :).

**Comment by sadatnfs** [comment]
Does anyone here have a preference on where I could put the example script? To start off, I'll literally be doing something like this for now:
```R
library(glmmTMB)
library(data.table)

N <- 150000
sim_data <- data.table(a = rnorm(N), b = rnorm(N))
sim_data[, y:= 0.3 + 0.5*a + 0.2*b + rnorm(N, 0, 0.25)]

system.time(model <- glmmTMB(data = sim_data, formula = y ~ 1 + a + b, verbose = F, control = glmmTMBControl(parallel = 1) ))
system.time(model <- glmmTMB(data = sim_data, formula = y ~ 1 + a + b, verbose = F, control = glmmTMBControl(parallel = 3) ))
```

**Comment by sadatnfs** [comment]
Question: should we put the `parallel` option in `glmmTMBcontrol` inside the `optCtrl` list with the iterations instead of not making it part of that list?

**Comment by sadatnfs** [comment]
@bbolker Just pushed a simple vignette (and also added a simple test in `test-control.R`)

**Comment by mebrooks** [comment]
I think @kaskr was talking about needing to see timing comparisons of the current version verses this branch applied to the exact same model without parallelization to show that it won't slow down cases that don't use parallelization.

**Comment by sadatnfs** [comment]
Thanks @mebrooks. I'll write up a shell script to install from each of the branches and run some simple models with timing.

**Comment by sadatnfs** [comment]
@mebrooks @kaskr thanks for your patience. Here's a script to install and run a simple model with and without threads (with output from `system.time`).

Have a great happy holiday everyone!

```bash
#!/bin/bash

## Function: Install glmmTMB
install_glmmTMB() {

    echo "Create base folder in home"
    mkdir ~/glmmTMB_libs
    mkdir ~/glmmTMB_libs/glmmTMB_serial
    mkdir ~/glmmTMB_libs/glmmTMB_parallel

    echo "Installing serial version"
    R -e "devtools::install_github('glmmTMB/glmmTMB/glmmTMB', build_vignettes = F, lib = '~/glmmTMB_libs/glmmTMB_serial')"

    echo "Installing parallel version"
    R -e "devtools::install_github('sadatnfs/glmmTMB/glmmTMB', build_vignettes = F, lib = '~/glmmTMB_libs/glmmTMB_parallel')"

    return 0
}


## Set up script for simulating data and running model
create_R_script() {
    echo '
        package_ver <- commandArgs(trailingOnly = TRUE)[1]
        num_threads <- commandArgs(trailingOnly = TRUE)[2]

        if(is.na(num_threads)) {
            num_threads <- 1
        }

        print(paste0("Loading ", package_ver, " package installation"))
        print(paste0("Using ", num_threads, " threads"))
        library(glmmTMB, lib.loc = paste0("~/glmmTMB_libs/glmmTMB_", package_ver) );

        print("Simulate data");
        N <- 4e5;
        xdata <- rnorm(N, 1, 2);
        ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);

        if(package_ver == "parallel") {
            system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
                verbose = FALSE, control = glmmTMBControl(parallel = num_threads)));
        } else {
            system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
                verbose = FALSE));
        }
        q("no")
        ' > ~/glmmTMB_libs/test_script.R

    return 0
}

## MAIN: Running different models
#### Argument: number of threads to input in parallel run
main() {
    echo "Install the serial and parallel glmmTMB packages"
    install_glmmTMB

    echo "Create R script with data simulation and model"
    create_R_script

    echo "Run model on serial package"
    Rscript ~/glmmTMB_libs/test_script.R "serial"

    echo "Run model on package package with a single thread"
    Rscript ~/glmmTMB_libs/test_script.R "parallel"

    echo "Run model on package package with $1 thread"
    Rscript ~/glmmTMB_libs/test_script.R "parallel" $1

    return 0
}

## Run with 5 threads
main 5
```

**Comment by mebrooks** [comment]
Thanks @sadatnfs for writing the tests. There seems to be a problem with the parallel version on my computer. Here is the output from the test
```
> 
Create R script with data simulation and model
Run model on serial package
[1] "Loading serial package installation"
[1] "Using 1 threads"
[1] "Simulate data"
   user  system elapsed 
  2.674   0.366   3.057 
Run model on package package with a single thread
[1] "Loading parallel package installation"
[1] "Using 1 threads"
[1] "Simulate data"
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
./test_parallel.script: line 55:  3528 Abort trap: 6           Rscript ~/glmmTMB_libs/test_script.R "parallel"
Run model on package package with 5 thread
[1] "Loading parallel package installation"
[1] "Using 5 threads"
[1] "Simulate data"
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
./test_parallel.script: line 55:  3533 Abort trap: 6           Rscript ~/glmmTMB_libs/test_script.R "parallel" $1
```

I also tried installing your fork in an R console session with the following
```
devtools::install_github('sadatnfs/glmmTMB/glmmTMB', build_vignettes = F)
```
then started a new session for R to get the new version.
```
library(glmmTMB)
N <- 4e5;
xdata <- rnorm(N, 1, 2);
ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
                verbose = FALSE, control = glmmTMBControl(parallel = 1)));
```
I ran the parallel version several times with 1 and 2 slaves (my computer only has 2 cores).
```
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE, control = glmmTMBControl(parallel = 1)));
   user  system elapsed 
  2.698   0.356   3.062 
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE, control = glmmTMBControl(parallel = 1)));
   user  system elapsed 
  2.531   0.361   2.892 
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE, control = glmmTMBControl(parallel = 1)));
   user  system elapsed 
  2.497   0.357   2.854 
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE, control = glmmTMBControl(parallel = 2)));
   user  system elapsed 
  3.613   0.546   2.224 
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE, control = glmmTMBControl(parallel = 2)));
   user  system elapsed 
  3.531   0.539   2.141 
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE, control = glmmTMBControl(parallel = 2)));
   user  system elapsed 
  3.518   0.548   2.138 
```
 Then I reinstalled the serial version and restarted the R session.

```
> library(glmmTMB)
> glmmTMBControl
function (optCtrl = list(iter.max = 300, eval.max = 400), profile = FALSE, 
    collect = FALSE) 
{
    namedList(optCtrl, profile, collect)
}
<bytecode: 0x7fc2889e0f00>
<environment: namespace:glmmTMB>
> N <- 4e5;
> xdata <- rnorm(N, 1, 2);
> ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE));
   user  system elapsed 
  2.613   0.354   2.967 
> N <- 4e5;
> xdata <- rnorm(N, 1, 2);
> ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE));
   user  system elapsed 
  2.342   0.350   2.667 
> N <- 4e5;
> xdata <- rnorm(N, 1, 2);
> ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
+                 verbose = FALSE));
   user  system elapsed 
  2.590   0.360   2.949 
```

Just eyeballing the means of these timings, I would say that the serial and parallel versions take roughly the same time when run with 1 slave and the parallel version is faster with 2 slaves. ..but of course more observations of the timing would help us be sure.

**Comment by mebrooks** [comment]
In case it helps debug the script, this is my session info
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.2

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_0.2.3

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-50     compiler_3.5.1  Matrix_1.2-14   TMB_1.7.15      Rcpp_1.0.0      splines_3.5.1   nlme_3.1-137   
 [9] grid_3.5.1      nloptr_1.2.1    lme4_1.1-19     lattice_0.20-35
```

**Comment by mebrooks** [comment]
I updated to the most recent version of R (3.5.2) and now the script works, but it could be the result of other updates. Here's my new sessionInfo
```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.2

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_0.2.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        compiler_3.5.2    nloptr_1.2.1      TMB_1.7.15        prettyunits_1.0.2 remotes_2.0.2    
 [7] tools_3.5.2       testthat_2.0.1    digest_0.6.18     lme4_1.1-19       pkgbuild_1.0.2    pkgload_1.0.2    
[13] memoise_1.1.0     nlme_3.1-137      lattice_0.20-38   rlang_0.3.0.1     Matrix_1.2-15     cli_1.0.1        
[19] curl_3.2          withr_2.1.2       desc_1.2.0        fs_1.2.6          devtools_2.0.1    rprojroot_1.3-2  
[25] grid_3.5.2        glue_1.3.0        R6_2.3.0          processx_3.2.1    sessioninfo_1.1.1 minqa_1.2.4      
[31] callr_3.1.0       magrittr_1.5      backports_1.1.3   ps_1.2.1          MASS_7.3-51.1     splines_3.5.2    
[37] usethis_1.4.0     assertthat_0.2.0  crayon_1.3.4     
```
And the output from the script
```
> 
Create R script with data simulation and model
Run model on serial package
[1] "Loading serial package installation"
[1] "Using 1 threads"
[1] "Simulate data"
   user  system elapsed 
  3.052   0.393   3.486 
Run model on package package with a single thread
[1] "Loading parallel package installation"
[1] "Using 1 threads"
[1] "Simulate data"
   user  system elapsed 
  2.757   0.363   3.123 
Run model on package package with 5 thread
[1] "Loading parallel package installation"
[1] "Using 5 threads"
[1] "Simulate data"
   user  system elapsed 
  9.204   3.296   4.041 
```
I had noticed with the old version also that it was slower with 5 threads than with 1 or 2. Here's a comparison of 1 vs 2 that I did by adding `main 2` to the script.
```
Create R script with data simulation and model
Run model on serial package
[1] "Loading serial package installation"
[1] "Using 1 threads"
[1] "Simulate data"
   user  system elapsed 
  2.613   0.366   2.995 
Run model on package package with a single thread
[1] "Loading parallel package installation"
[1] "Using 1 threads"
[1] "Simulate data"
   user  system elapsed 
  2.632   0.344   2.978 
Run model on package package with 2 thread
[1] "Loading parallel package installation"
[1] "Using 2 threads"
[1] "Simulate data"
   user  system elapsed 
  3.826   0.622   2.426 
```

**Comment by sadatnfs** [comment]
> Thanks @sadatnfs for writing the tests. There seems to be a problem with the parallel version on my computer. Here is the output from the test
> 
> ```
> > 
> Create R script with data simulation and model
> Run model on serial package
> [1] "Loading serial package installation"
> [1] "Using 1 threads"
> [1] "Simulate data"
>    user  system elapsed 
>   2.674   0.366   3.057 
> Run model on package package with a single thread
> [1] "Loading parallel package installation"
> [1] "Using 1 threads"
> [1] "Simulate data"
> OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
> OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
> ./test_parallel.script: line 55:  3528 Abort trap: 6           Rscript ~/glmmTMB_libs/test_script.R "parallel"
> Run model on package package with 5 thread
> [1] "Loading parallel package installation"
> [1] "Using 5 threads"
> [1] "Simulate data"
> OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
> OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
> ./test_parallel.script: line 55:  3533 Abort trap: 6           Rscript ~/glmmTMB_libs/test_script.R "parallel" $1
> ```
> I also tried installing your fork in an R console session with the following
> 
> ```
> devtools::install_github('sadatnfs/glmmTMB/glmmTMB', build_vignettes = F)
> ```
> then started a new session for R to get the new version.
> 
> ```
> library(glmmTMB)
> N <- 4e5;
> xdata <- rnorm(N, 1, 2);
> ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
> system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
>                 verbose = FALSE, control = glmmTMBControl(parallel = 1)));
> ```
> I ran the parallel version several times with 1 and 2 threads (my computer only has 2 cores).
> 
> ```
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE, control = glmmTMBControl(parallel = 1)));
>    user  system elapsed 
>   2.698   0.356   3.062 
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE, control = glmmTMBControl(parallel = 1)));
>    user  system elapsed 
>   2.531   0.361   2.892 
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE, control = glmmTMBControl(parallel = 1)));
>    user  system elapsed 
>   2.497   0.357   2.854 
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE, control = glmmTMBControl(parallel = 2)));
>    user  system elapsed 
>   3.613   0.546   2.224 
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE, control = glmmTMBControl(parallel = 2)));
>    user  system elapsed 
>   3.531   0.539   2.141 
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE, control = glmmTMBControl(parallel = 2)));
>    user  system elapsed 
>   3.518   0.548   2.138 
> ```
> Then I reinstalled the serial version and restarted the R session.
> 
> ```
> > library(glmmTMB)
> > glmmTMBControl
> function (optCtrl = list(iter.max = 300, eval.max = 400), profile = FALSE, 
>     collect = FALSE) 
> {
>     namedList(optCtrl, profile, collect)
> }
> <bytecode: 0x7fc2889e0f00>
> <environment: namespace:glmmTMB>
> > N <- 4e5;
> > xdata <- rnorm(N, 1, 2);
> > ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE));
>    user  system elapsed 
>   2.613   0.354   2.967 
> > N <- 4e5;
> > xdata <- rnorm(N, 1, 2);
> > ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE));
>    user  system elapsed 
>   2.342   0.350   2.667 
> > N <- 4e5;
> > xdata <- rnorm(N, 1, 2);
> > ydata <- 0.3 + 0.5*xdata + rnorm(N, 0, 0.25);
> > system.time(run_model <- glmmTMB(formula = ydata ~ 1 + xdata, 
> +                 verbose = FALSE));
>    user  system elapsed 
>   2.590   0.360   2.949 
> ```
> Just eyeballing the means of these timings, I would say that the serial and parallel versions take roughly the same time when run with 1 thread and the parallel version is faster with 2 threads. ..but of course more observations of the timing would help us be sure.


Thanks @mebrooks ! It's super weird that the first time you tried with the bash script, you got all the OMP library issues, but then when you did it manually, you did not. 

For the timing of 5 threads versus 2 in timing, did you have `N=4e5` for both those instances? My initial thought was that maybe having 5 threads for a smaller number of observation had unnecessary overhead and so it took longer than 2 threads.

Finally, I was looking at the Travis logs and it had a false positive on the build status because it actually failed to load the library (but still didn't fail the Travis job). The error (https://travis-ci.com/sadatnfs/glmmTMB/jobs/166862725#L1280) looks to be relevant to the OpenMP libraries, so I'm going to try a fix which I had in a previous commit (but removed once it looked redundant) where I `include` the OMP headers in the C++ file, and see how Travis behaves with that.

**Comment by sadatnfs** [comment]
Aha, found this error after I hardcoded `-fopenmp` in all the CXX flags in my Travis config. I'll need to check how can I not make Travis be sad with OpenMP flags.

https://travis-ci.com/sadatnfs/glmmTMB/jobs/168512992#L1280-L1282

**Comment by sadatnfs** [comment]
Update: it turns out that older basic versions of the compiler that comes with Ubuntu:Trusty does *not* have the capabilities of running OMP tests, so I opened a PR with an upgrade to Travis (https://github.com/glmmTMB/glmmTMB/pull/432), and have made the same changes to this branch as well. I had to fix a typo in my `test-control` so I took the chance to add in the Travis fix here as well (hopefully the other PR runs through all green first and foremost!). 

Thanks all!

**Comment by bbolker** [comment]
What's the status of this?  Can we safely merge? Should we?  Is there a way we can make sure this is backward-compatible with older versions of R (I don't like to break back-compatibility without good reasons ...)?

**Comment by sadatnfs** [comment]
Hey @bbolker, yeah this definitely should be backwards compatible. However, Travis was returning false positives when we had OpenMP flags, and so I opened #432 in order to upgrade the Travis backend to use Xenial. TMB's repo also upgraded their Travis backend to Xenial.

If you merge #432 and then this (conditional on you feeling that the Travis outputs look satisfactory to you), then yeah please feel free to merge both #432 and this!

Thanks!

**Comment by sadatnfs** [comment]
Just fixed the merge conflict!

**Comment by bbolker** [comment]
#432 is merged.  Any further commentary/testing needed?  (I have **not** tested these versions myself!)

**Comment by sadatnfs** [comment]
Oh wow.. for some reason my comment from 2 days ago never got submitted. Sorry about that @bbolker , yes please merge this in! 
@mebrooks since you ran this version of the package with some of your own testing, do you have anything to add here?

**Comment by bbolker** [comment]
I'm still worried about this.  Travis builds are still segfaulting during the vignette build.

**Comment by sadatnfs** [comment]
I'm gonna look at that in the next few days over the weekend. I just found that I can run Travis builds locally in a Docker without having to test every change through the CO service here. So technically if I can replicate the problem, then I can look for its solution.

**Comment by sadatnfs** [comment]
@bbolker from scouring around, this looks like a recurring issue with Travis timing out on long running jobs. I'm gonna change a few things and retrigger Travis to see if that helps.

**Comment by sadatnfs** [comment]
Yep, it's definitely `travis_wait`. I took that out in my latest commit and it passed properly.

I'm gonna put in `travis_wait 100` and see if the error comes back again. Was there a reason why `travis_wait` was put in to begin with?

**Comment by bbolker** [comment]
I don't think we need `travis_wait` if it works. Can you clarify why the builds are taking 83 minutes? Is that ridiculous amounts of package rebuilding?  Do they take that long after packages are up-to-date/cached? Or is there something else I'm meeting?

**Comment by sadatnfs** [comment]
That long build was from some commit more than a month ago; that has definitely stopped happening now.

Looking at logs, every step did finish successfully but Travis just didn't finish the jobs for like an extra 70 minutes. That definitely hasn't been the case for any of the tests recently.

That being said, yeah `travis_wait` is DEFINITELY the culprit for that false positive end (confirmed with the latest commit test). I took that out of the latest commit, and also added an extra field in DESCRIPTIONS for setting system requirements to use GNU make, as per R package guidelines, since that's something Kasper mentioned up there to think about.

This can be merged now, no more changes on my end! :)

**Comment by bbolker** [comment]
thanks!

**Comment by sadatnfs** [comment]
@bbolker could we perhaps re-trigger the build on the master branch of glmmTMB? The R-devel build seemed to have kicked the bucket right at the apt-get call (even though release and devel are both in the same Ubuntu environment). 

I just restarted the build on my forked repo, and both release and devel went past that line of build, so I think this failure just might have been spurious?

**Pull request merged**
