### PR TITLE
Pr weights

### PR DESCRIPTION
**Pull request by bbolker**
this is a modification of PR #490 (I was able to make a local branch but don't know how to push my changes back into that PR)

### CODE REVIEW

**Comment by bbolker** [comment]
@mebrooks , do you want to take a look? (I could just merge it but I kind of feel it should be glanced at by one other package author before merging ...)

**Comment by mebrooks** [comment]
Shit. RStudio did that whitespace thing in my commit, but didn't show me in the diff! I'll try to undo it.

**Comment by mebrooks** [comment]
@kaskr, are all these whitespace changes going to show up in the history anyway because they're done and undone in separate commits?

**Comment by kaskr** [comment]
@mebrooks Yeah you would have to squash the two commits (add space / revert space) to a single commit on a new branch. Github has the feature to squash an entire PR but that's not a good idea in this case. It's fairly easy to clean up the mess from the command line using `git rebase -i`.

**Comment by mebrooks** [comment]
OK. Next time we can avoid it, but for now I guess we should go with this tangle of commits. Do you want to accept it @kaskr?

**Comment by kaskr** [comment]
@mebrooks Yes, I decided the 'squash and merge' wasn't too bad - see history.

**Pull request merged**
