### PR TITLE
Add TMB_SAFEBOUNDS to compilation

### PR DESCRIPTION
**Pull request by kaskr**
Can sometimes detect bugs in the C++ code...

### CODE REVIEW

**Comment by bbolker** [comment]
(1) this already found a bounds error! While testing `REML`

**Comment by kaskr** [comment]
I'm just realizing we can't enable safe bounds by default due to CRAN policy... Too bad

**Comment by kaskr** [comment]
I have never noticed a measurable performance hit due to safe bounds.

**Comment by kaskr** [comment]
FWIW `make quick-install` has safe bounds enabled, so no need for this PR

**Pull request merged**
