### PR TITLE
add prediction of latent variables.

### PR DESCRIPTION
**Pull request by bbolker**
added a possible prediction type `predict(., type = "latent")`. This is potentially redundant with `ranef()`. I've been encountering some problems trying to extract latent variables reliably for reduced-rank models; not quite sure why this is happening (`rr()` models are a bit special in that they are the only case where the latent variables are modified *in place* ... that said, I would have expected to see *either* the "spherical" (prior/unconditional distribution is iid N(0,1)) *or* the "nonspherical" (spherical values multiplied by the factor loading matrix) ... possibly ranef() is sticking the spherical values (which are of lower dimension than the nonspherical ones) into a random-effects matrix of the wrong dimension?

In any case, sorry that's a bit stream-of-consciousness, this is something of a placeholder.  We need to fix `ranef()` so that it does something sensible for `rr()` models in any case; if it can be done with less messing around (adding REPORT/ADREPORT for `b`), then that might be better.

### CODE REVIEW

**Comment by bbolker** [comment]
`ranef()` is now fixed (I think), and I've added some stuff to the covstruct vignette (at least partially addresses #1012). This could be ready to merge now, if nothing is obviously broken ...

**Comment by mebrooks** [comment]
There's a problem with the `covstruct` vignette, but I can't see why. When I try to run it, I get this

```
Quitting from lines 697-700 [get-fl] (covstruct.rmd)
                                                                                                                      
Error in `source()`:
! empty file/url name
Backtrace:
 1. base::source(system.file("misc", "extract_rr.R", package = "glmmTMB"))
Execution halted
```
To me, this looks the same as all the other calls of `source(system.file(`.

**Comment by bbolker** [comment]
I think I mistakenly had a pattern matching "misc" in `.Rbuildignore`.  Removed it, we'll see if that fixes the GH actions.

**Comment by bbolker** [comment]
@mebrooks, please take another look (I mistakenly cherry-picked something to the master branch that depended on the `spider_long` data  set introduced in this PR ... rather than cherry-pick that as well it would be easier to merge this branch ... thanks ...)

**Pull request merged**
