### PR TITLE
return eta_predict

### PR DESCRIPTION
**Pull request by bbolker**
This is in response to #696 ; it returns `eta_predict` as well as `mu_predict`.  Some loose ends that might want to be discussed/dealt with before merging:

- right now the TMB file returns *both* `eta_predict` and `mu_predict`. Could that be a computational/memory burden with a very large data set? Is it worth adding complexity/doing extra work to add a flag that tells TMB whether the predicted value is returned on the link (`eta`) or response (`mu`) scale? (Except that we will probably never revisit this, it seems reasonably harmless to do it this way for now ...)
- I've implemented "clamping" on the cloglog inverse link, as in R's `make.link("cloglog")$linkinv`. Is there any reason there is *not* a good idea? (e.g. computational cost). We don't need it as much as R does because we use the 'robust' versions of the reponse distributions (i.e. we never back-transform all the way to the probability scale), but it could make some computations more reliable/more comparable with results from R (e.g. if someone requests predictions on the response (probability) scale and then uses them in `dbinom()` calculations)
- I'm not sure I've tested the 'zlink' results thoroughly
-

### CODE REVIEW

**Comment by kaskr** [comment]
Returning `eta_predict` is an improvement (I never understood why one would ever want to back transform `mu_predict` from within `predict()` when we already have it available for free without lack of accuracy).

However, I'm very much against the clamping part (sorry!).
When `1-p` evaluates to `1` it signifies lack of accuracy which is useful information that should be taken seriously. Clamping hides the problem rather than solving it.

**Comment by bbolker** [comment]
That's why I asked.  I've reverted the clamping.  (If someone really wants clamped results they can use R's inverse-cloglog link: `make.link("cloglog")$linkinv(predict(., type="link"))`

**Comment by bbolker** [comment]
Right now there is a integer `doPredict` flag that is equal to `as.numeric(se.fit)` (i.e. 1 to enable ADREPORT, 0 otherwise).  What do you think about making it 

- 0 if no prediction
- 2 if prediction on the link scale
- 1 if prediction on the response scale ?

This means that we don't have to change the overall structure of the API, and 1 maintains its earlier meaning [although I'm not 100% sure of backward compatibility in all scenarios .. ?]

**Comment by bbolker** [comment]
I've now implemented my suggestion above.

**Pull request merged**
