### PR TITLE
logLik=NA when pdHess=FALSE

### PR DESCRIPTION
**Pull request by mebrooks**

### CODE REVIEW

**Comment by mebrooks** [comment]
I think I fixed it now so that it should work with `glmmTMB(..., se=FALSE)`. However, now it's failing on Travis (RVERSION=devel) with 
```
* checking package dependencies ... ERROR
Packages required but not available: ‘TMB’ ‘lme4’ ‘RcppEigen’
Packages suggested but not available:
  ‘knitr’ ‘ggplot2’ ‘mlmRev’ ‘bbmle’ ‘pscl’
```

**Comment by mebrooks** [comment]
@mmaechler, if the Travis check is only failing on `RVERSION=devel`, is it safe to assume the problem is coming from the development version of R?

**Comment by mmaechler** [comment]
Well, "only" is maybe an understatement:  That version usually works for all CRAN packages (that the released version works) and it is *the* plan for the next version of R...

However, I do think it will be a Travis problem where for some reason "R devel" version is partly broken, because I cannot see why  lme4 or RcppEigen  should not be available there... but then I usually don't use Travis but test on my computers .. and there lme4 does (almost always) work with R-devel.

So while I'd like to defend the quality of R-devel (which is usually also the *fastest* version of R), I agree that a failure like the above should not mean a real problem with our package.

**Comment by mebrooks** [comment]
Ok great! Thanks. I'm going to merge this in then. This should take care of #201

**Comment by bbolker** [comment]
I would agree that (in my experience) when the Travis build fails on only one out of three R versions, it's *usually* a Travis glitch rather than a real cross-version incompatibility.

**Pull request merged**
