### PR TITLE
New se fix

### PR DESCRIPTION
**Pull request by bbolker**
This branch was written while investigating #324. In the process of investigating, I (1) added a `type` argument to `predict.glmmTMB`; (2) **removed the zitype argument** (it's now handled as part of `type`); (3) **changed the default predict() to return type="link"** for consistency with `glm()`; (4) added link-function info to all (?) of the `glmmTMB` family functions. Changes 2 and 3 are not backward-compatible, but I think they're a good idea nonetheless.

### CODE REVIEW

**Comment by strengejacke** [comment]
The API-change makes sense to me. Looks like you can now easily handle glmmTMB objects in the same way as glm-objects, plus the zero-inflation options.

**Comment by kaskr** [comment]
Not sure what are the consequences of changing the predict defaults. Here are some more to consider:

* Code snippets of the paper https://journal.r-project.org/archive/2017/RJ-2017-066/RJ-2017-066.pdf could be affected.
* Vignette `covstruct.rmd` is probably affected.

**Comment by bbolker** [comment]
I think we do now have `$linkinv`, etc. components in the families ... so `family(fitted_model)$linkinv` should get the inverse link function.  Let me know if I missed something.

**Comment by bbolker** [comment]
fixed covstruct vignette.  Should we add a warning (for now) whenever `predict()` is called with `type` not explicitly specified?

**Comment by strengejacke** [comment]
You could also deprecate `zitype` first, so it would not radically break backwards compatibility, and simply pass`zitype` over to `type`.

**Comment by strengejacke** [comment]
(or did you mean exactly that?)

**Comment by bbolker** [comment]
No, I agree that deprecating (rather than eliminating) `zitype` is a better idea.

**Comment by bbolker** [comment]
Bump (for those watching this PR). I have in mind some logic like:

```
if (missing(type)) {
   warning("default predict type is now 'link'; use type='response' for back-compatible behaviour or type='link' to avoid this warning")
}
```

We could then leave that warning in place for one or two releases ... ? Alternatively/in addition we could set up an `options(glmmTMB_response_type)` to allow users to adjust global settings ... ?

**Comment by bbolker** [comment]
What did people think about the advisability of always warning users when `type` is not explicitly specified?

**Comment by kaskr** [comment]
It'll get too annoying on the long run with the warning. As long as the new behaviour is documented in vignettes and highlighted in the NEWS I think we're good.

**Comment by koenvanbenthem** [comment]
It'll get annoying, but I think a warning would be good. Now everybody may read the news or vignettes thoroughly when installing a new version.

Would it be possible to create a global option that determines whether the warning is displayed or not? We then simply add a small function that users can run to change the option value and thereby disable the warning message. (e.g. warning will only be displayed as long as options('display_glmmTMB_type_warning') == TRUE)

**Comment by bbolker** [comment]
I added this  in 9c0bdeb (the option is called `glmmTMB.default.response` or something like that), but I'm not sure whether it's worth adding now that version 0.2.1 has already been pushed to CRAN ... ?

**Pull request merged**
