### PR TITLE
Hetar1

### PR DESCRIPTION
**Pull request by bbolker**
See https://github.com/glmmTMB/glmmTMB/issues/1095.

Haven't written any documentation or tests yet.

### CODE REVIEW

**Comment by mebrooks** [comment]
This seems ok, except for some conflicts. The chunks of code are pretty big and I don't have my big monitor today, so they seem difficult to address.

**Comment by bbolker** [comment]
For the record this seems to be OK at present *except for printing*.

**Comment by mebrooks** [comment]
Should we make an issue to discuss covstruct output? It seems like a big intertwined messy topic.

**Comment by bbolker** [comment]
Yes ...

**Pull request merged**
