### PR TITLE
check for REML issues with anova()

### PR DESCRIPTION
**Pull request by bbolker**
addresses (maybe resolves?) #686

### CODE REVIEW

**Comment by bbolker** [comment]
ping @mebrooks @kaskr : I think this is fairly harmless/OK to commit (only affects `anova()` method, can't *think* of any strange edge cases)

**Comment by mebrooks** [comment]
It causes some problems for my computer. I will try to come back to this later, but I don't have time at this minute. I was just trying to do a quick test between other things.
```
~/Documents/glmmTMB development/glmmTMB make test
echo "devtools::test('glmmTMB')" | R --slave
Error in get(genname, envir = envir) : object 'testthat_print' not found
Loading glmmTMB
Testing glmmTMB
✔ |  OK F W S | Context
✔ |   3       | Anova [0.4 s]
✔ |  13       | VarCorr [5.7 s]
✔ |   2       | alternative optimizers
✔ |  33       | basics [2.7 s]
✔ |  15       | trickier examples [4.0 s]
✖ |   0 2     | bootMer [0.7 s]
────────────────────────────────────────────────────────────────────────────────
test-bootMer.R:12: error: Bernoulli responses
invalid 'add' argument
Backtrace:
 1. lme4::bootMer(m, fun, nsim = 2, seed = 101) tests/testthat/test-bootMer.R:12:4
 2. glmmTMB:::FUN(x)
 4. glmmTMB::predict.glmmTMB(x)

test-bootMer.R:21: error: Bernoulli responses
invalid 'add' argument
Backtrace:
 1. lme4::bootMer(m, fun, nsim = 2, seed = 101) tests/testthat/test-bootMer.R:21:4
 2. glmmTMB:::FUN(x)
 4. glmmTMB::predict.glmmTMB(x)
────────────────────────────────────────────────────────────────────────────────
✔ |   3       | glmmTMBControl [4.6 s]
✖ |   2 1     | disp [1.2 s]
────────────────────────────────────────────────────────────────────────────────
test-disp.R:40: error: predict dispersion
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(...) tests/testthat/test-disp.R:40:4
 5. glmmTMB::predict.glmmTMB(m0, type = "disp")
────────────────────────────────────────────────────────────────────────────────
✔ |  13       | emmeans [5.3 s]
✔ |   2       | effects [0.6 s]
✔ |   1       | test edge cases [0.5 s]
✔ |   3       | basic examples [1.2 s]
✖ |   0 1     | alternative binomial specifications [0.5 s]
────────────────────────────────────────────────────────────────────────────────
test-families.R:26: error: binomial
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(predict(mod1), predict(mod2)) tests/testthat/test-families.R:26:4
 5. glmmTMB::predict.glmmTMB(mod1)
────────────────────────────────────────────────────────────────────────────────
✔ |   7       | non-integer count warnings [1.2 s]
✔ |  31       | fitting exotic families [19.0 s]
✖ |   2 1     | trunc compois [0.2 s]
────────────────────────────────────────────────────────────────────────────────
test-families.R:329: error: truncated_compois
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(...) tests/testthat/test-families.R:329:8
 5. glmmTMB::predict.glmmTMB(tcmp1, type = "response")
────────────────────────────────────────────────────────────────────────────────
✖ |   2 1     | compois [0.2 s]
────────────────────────────────────────────────────────────────────────────────
test-families.R:339: error: compois
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(...) tests/testthat/test-families.R:339:8
 5. glmmTMB::predict.glmmTMB(cmp1, type = "response")
────────────────────────────────────────────────────────────────────────────────
✔ |   2       | genpois [0.2 s]
✔ |   6       | tweedie [1.9 s]
✔ |  12       | link function info available
✖ |   1 1     | link info added to family [0.5 s]
────────────────────────────────────────────────────────────────────────────────
test-families.R:428: error: (unknown)
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(predict(glm.D93), predict(glm.D93B)) tests/testthat/test-families.R:428:0
 5. glmmTMB::predict.glmmTMB(glm.D93)
────────────────────────────────────────────────────────────────────────────────
✔ |  16       | formula parsing
✖ |  18 1     | mapopt
────────────────────────────────────────────────────────────────────────────────
predict.R:179: error: predict works with mapped params
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(...)
 6. glmmTMB::predict.glmmTMB(m1, se.fit = TRUE)
────────────────────────────────────────────────────────────────────────────────
✔ |   4       | alternate optimizers
✖ |  48 2   1 | basic methods [5.0 s]
────────────────────────────────────────────────────────────────────────────────
test-methods.R:19: error: Fitted and residuals
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(length(fitted(fm2)), nrow(sleepstudy)) tests/testthat/test-methods.R:19:4
 5. glmmTMB::fitted.glmmTMB(fm2)
 7. glmmTMB::predict.glmmTMB(object, type = "response", fast = TRUE)

test-methods.R:72: error: Predict
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(predict(fm2), predict(fm2, newdata = sleepstudy)) tests/testthat/test-methods.R:72:4
 5. glmmTMB::predict.glmmTMB(fm2)

test-methods.R:158: skip: terms back-compatibility
Reason: skip until TMB fits are back-compatible
────────────────────────────────────────────────────────────────────────────────
✖ |   2 1     | simulate consistency with glm/lm
────────────────────────────────────────────────────────────────────────────────
test-methods.R:336: error: residuals from binomial factor responses
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(residuals(fm2Bf), residuals(fm2Bn)) tests/testthat/test-methods.R:336:4
 5. glmmTMB::residuals.glmmTMB(fm2Bf)
 7. glmmTMB::fitted.glmmTMB(object)
 9. glmmTMB::predict.glmmTMB(object, type = "response", fast = TRUE)
────────────────────────────────────────────────────────────────────────────────
✖ |  13 1   1 | Ranef etc. [19.6 s]
────────────────────────────────────────────────────────────────────────────────
test-methods.R:517: error: trunc nbinom simulation
invalid 'add' argument
Backtrace:
 1. testthat::expect_equal(fitted(m1), c(4.24835425529159e-18, 0.367879441171442)) tests/testthat/test-methods.R:517:8
 5. glmmTMB::fitted.glmmTMB(m1)
 7. glmmTMB::predict.glmmTMB(object, type = "response", fast = TRUE)

test-methods.R:524: skip: trunc nbinom sim 2
Reason: empty test
────────────────────────────────────────────────────────────────────────────────

══ Terminating early ═══════════════════════════════════════════════════════════
Too many failures
```

**Comment by bbolker** [comment]
@mebrooks: I'm not seeing this. I did just merge `master` back into this branch, which might help (I think the "'add' argument" error is coming from the `on.exit()` stuff we fixed recently, which would also be more likely to break under 3.6.3).

- make sure your `testthat` is up to date?
- try again?

**Comment by mebrooks** [comment]
Yep. It worked this time. Thanks for fixing the add `on.exit()` issue.

**Pull request merged**
