### PR TITLE
Tex files

### PR DESCRIPTION
**Pull request by mebrooks**

### CODE REVIEW

**Comment by bbolker** [comment]
I was going to merge as soon as checks finished but I guess it's getting late :-)

**Comment by mebrooks** [comment]
I don't want to _move fast and break things_, but we have been testing a lot and I'm about to test the master branch again now.  I think it's complete not, right?

**Comment by bbolker** [comment]
Yes, I think we're ready to go.

**Comment by mebrooks** [comment]
It's getting errors on Windows about vignettes. Is that what we expect? 
https://win-builder.r-project.org/l0jM57ZOYE8O/
https://win-builder.r-project.org/JQr1us44REN2/
https://win-builder.r-project.org/CydPFEzDpg3o/

The following one is a new error to me:
```
* checking re-building of vignette outputs ... ERROR
Check process probably crashed or hung up for 20 minutes ... killed
Most likely this happened in the example checks (?),
if not, ignore the following last lines of example output:
> noSpecials(y~us(1|f), debug=TRUE)
y ~ us(1 | f)
[1] "not special"
y
us(1 | f)
y ~ 1
> noSpecials(y~us+1)  ## should *not* delete unless head of a function
y ~ us + 1
> noSpecials(~us+1)   ## should work on a one-sided formula!
~us + 1
> 
> 
> 
> base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
> base::cat("splitForm", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
> ### * <FOOTER>
> ###
> cleanEx()
> options(digits = 7L)
> base::cat("Time elapsed: ", proc.time() - base::get("ptime", pos = 'CheckExEnv'),"\n")
Time elapsed:  21.2 0.47 21.56 NA NA 
> grDevices::dev.off()
null device 
          1 
> ###
> ### Local variables: ***
> ### mode: outline-minor ***
> ### outline-regexp: "\\(> \\)?### [*]+" ***
> ### End: ***
> quit('no')
======== End of example output (where/before crash/hang up occured ?) ========
```
Still checking on Solaris...

**Comment by bbolker** [comment]
ugh, ugh, ugh.  I did make *minor* changes in both `glmmTMB.Rnw` (the "getting started" vignette) and `model_evaluation.Rnw`; I did take out a `cache=TRUE` [here](https://github.com/glmmTMB/glmmTMB/commit/f5968d72ce71445e0fbcaa5a6f6f4d0df634b2ce#diff-05f92edbe77fa1b42e0b66b9fec881cc39d52323d92ee7b1f475ad7a927efdf0L257), but I don't see how that could make a difference (because there shouldn't be a cached copy on winbuilder??)

You can see all of the recent changes in these two files:

```
git diff HEAD~10..HEAD -- glmmTMB/vignettes/model_evaluation.Rnw
git diff HEAD~10..HEAD -- glmmTMB/vignettes/glmmTMB.Rnw
```

(`HEAD~10` is 10 commits ago, which captures the right time frame).  It's hard to see what could be screwing things up ??)

**Comment by mebrooks** [comment]
It passes checks on DTU's cluster and[ on Solaris](https://builder.r-hub.io/status/glmmTMB_1.1.2.tar.gz-e785d47c797a4996895b057d870c0833). I'm checking Windows on r-hub this time. I'll do reverse dependencies next.

**Comment by mebrooks** [comment]
rhub says it's fine [on Windows](https://builder.r-hub.io/status/glmmTMB_1.1.2.tar.gz-dc624d7e5e264bcdb23e6bed8129806b).

**Comment by bbolker** [comment]
Cool. (I'm re-running it on win-builder, wondering if it might be a transient problem ...)  How long does checking reverse dependencies take?  If I were you I'd probably cue up the submission and get ready to hit the button as soon as the rev-dep checks are done ...

**Comment by bbolker** [comment]
Ugh, win-builder fails again.

I'm going to try the following sequence:

```
git checkout HEAD~10  ## enters "detached head state", i.e. temporary copy of old version
sed -i -e "s/molliebrooks/bbolker/" glmmTMB/DESCRIPTION  ## change 'maintainer' email
R CMD build glmmTMB
## <upload glmmTMB_1.1.2.tar.gz to win-builder (can this be done programmatically?) >
```

This will test whether the problem is indeed new.  If so, we could use `git bisect` to find the commit that broke things, although it's awfully tedious when each iteration takes 30-60 minutes to evaluate ...

I don't know if we can get away with a submission that says "this works OK on r-hub/windows but not on win-builder". If we were desperate we could submit a version that we weren't sure about; it might work, and even if it doesn't we formally get in within the deadline/reset the clock for resubmission. On the other hand, it's sort of a waste of CRAN maintainers' time if we're pretty sure it's *not* going to work ...

**Comment by mebrooks** [comment]
Thanks for checking that. [One entry says]( https://stat.ethz.ch/pipermail/r-package-devel/2018q1/002256.html) it's possible to ask that the vignettes not be build on CRAN.

The reverse dependency checks should be finished in 5 minutes.

**Comment by mebrooks** [comment]
There are no problems with reverse dependencies. I'm ready to submit anytime. 

I might just explain the vignette issue in the comments section. Does that sound ok? I'm guessing that CRAN time is Austria or Switzerland, so the deadline is in 15 minutes, but I could be wrong.

**Comment by bbolker** [comment]
Sorry, I missed this. I think you should go ahead and submit, if you haven't already. (I don't remember if the due date was 7 July or 8 July - I may have it mixed up because one of my packages needed a resubmission by 8 July; I also don't know if "before <date>" means before the *beginning* or the *end* of the day; finally, I don't think the CRAN maintainers will archive glmmTMB if we were supposed to submit a revised version by midnight CET and ended up submitting 30-60 minutes after that ...)

**Comment by mebrooks** [comment]
The email from CRAN said before 2021-07-08, so I went ahead and submitted it at midnight. I recently had a mixup with another deadline when I was asked to do something "by X date" and I thought that meant by the end of day X and they meant before that day. I'm used to deadlines being at the end of a day (e.g. 5pm local time for NSF grants). I included comments about DHARMa on Solaris and about vignettes on CRAN, with links to the passing r-hub checks to show that we made a good effort. I'll update when I hear back tomorrow.

**Comment by bbolker** [comment]
In the meantime I wrote a [script](https://github.com/glmmTMB/glmmTMB/blob/master/misc/autowinbuilder.sh) that automatically checks out a previous version of the repo; hacks the DESCRIPTION file to replace the maintainer e-mail address; builds the package; uploads it to win-builder; restores the repo to its latest version; and checks the win-builder queue to make sure the upload worked.  It will still be slow, but if we have to dink around more with checking a series of versions on win-builder that will hopefully make the process a little bit less painful ...

**Pull request merged**
