### PR TITLE
Hdiag cov2

### PR DESCRIPTION
**Pull request by bbolker**
This PR implements a basic version of homogeneous diagonal covariance structure (as `homdiag()`), as a good thing in itself and a step toward implementing #704.  I strongly suspect that the actual code could be cleaned up; I'm not very clear on which TMB components are vectorized, and how to do basic operations (like the equivalent of `x = rep(y, n)` in R).

### CODE REVIEW

**Comment by bbolker** [comment]
bump @kaskr @skaug ? It would be nice to add this, but also nice to see if my ugly code can be made slightly less ugly ...

**Comment by kaskr** [comment]
@bbolker My first thought would have been to implement this using maps on the existing  `diag_covstruct`. Any reason not to do that?

**Comment by mebrooks** [comment]
This passes `make test` (same warnings as in master branch).

**Comment by bbolker** [comment]
OK. For what it's worth, the reason not to use `map=` is that it simplifies the user interface a lot; the user doesn't have to figure out how to use `map`/which parameters in `theta` should be mapped together/etc.

**Comment by bbolker** [comment]
I'm going to go ahead and merge.

**Pull request merged**
