### PR TITLE
Extend RE form

### PR DESCRIPTION
**Pull request by bbolker**
This PR addresses a lot of (too many?) different things, primarily the need for finer control of random effects when predicting/simulating (i.e., allowing choices of `re.form` that specify particular RE terms or sub-terms). It's definitely not finished; I'm opening this PR as a place for discussion. 

What this does/should do:

- allow specification of `re.form` by a formula, even one specifying a submodel, e.g. if the RE in a model is `(1 + f1 | g1) + (1 + f2 | g2)`, then `re.form = ~ (1 | g1)` should specify that *only* the latent variables corresponding to intercept variation among `g1` levels should be included in predicted values, (?? or in simulated values ??). I could have sworn I had started to implement a bunch of stuff here (parsing names of terms and matching them up with elements of `b`) but now I can't find it anywhere (!!??!!)  I see this referred to in [this issue as well](https://github.com/glmmTMB/glmmTMB/issues/861). Guess I have to try to remember what my general approach was for identifying the subset of `b` corresponding to a particular subset of variables ...
- map (i.e., fix) relevant sets of `b` values when simulating or predicting (or setting population-level effects to zero), especially when fixed effect parameters may have been modified (`simulate.glmmTMB` docs currently say that it's not possible to condition on random effects when simulating ...) &mdash; especially important to prevent re-evaluation of the inner optimization in Laplace approximation. The [map_b branch](https://github.com/glmmTMB/glmmTMB/tree/map_b) should also probably get rolled in ...

### CODE REVIEW

**Comment by mebrooks** [comment]
There's 1 failed test and 15 warnings all comming from `test-simulate_new.R`. @bbolker, I'll leave it to you since I don't want to change what you intended to test.

**Comment by bbolker** [comment]
Looking at it now.

**Comment by bbolker** [comment]
I think I've fixed this, although it's slightly scary to be working on a release in a hurry. (However, I think that anything I screw up will only affect edge cases of `simulate_new()` that no-one else is using, so it will be my/my student's problem ...)  Passes tests locally, waiting for GH actions to finish.

**Comment by mebrooks** [comment]
Do you want to resolve the conflicts or should I have a look? I may have caused them when I merged the `prop2_covstruct` branch a few minutes ago.

**Comment by bbolker** [comment]
I'll take a look.

**Comment by bbolker** [comment]
:tada:

**Pull request merged**
