### PR TITLE
bump TMB version dep to 1.7.13 (#331)

### PR DESCRIPTION
**Pull request by bbolker**

### CODE REVIEW

**Comment by mebrooks** [comment]
I don't know what is causing this error. I installed this branch on my computer and then ran the line of code that Travis is complaining about. 
```
salamander_prof1 <- readRDS(system.file("example_files","salamander_prof1.rds",package="glmmTMB"))
```
I don't get any errors from it.

**Comment by bbolker** [comment]
OK, I would suggest that we try accepting the PR and then clean up the mess if necessary.  Alternatively, we could delete the branch and try again.

**Comment by mebrooks** [comment]
Ok. I'm ok with accepting the PR, but I'll have to leave my computer soon and might not be available to help clean up the mess. @bbolker, go for it if you want to try.

**Comment by bbolker** [comment]
I'm feeling nervous, I'll try a clean branch instead.

**Pull request closed without merging**
