### PR TITLE
work around variation in downstream methods exports

### PR DESCRIPTION
**Pull request by bbolker**
attempt to condition tests based on what downstream methods are actually available ...

### CODE REVIEW

**Comment by mebrooks** [comment]
The [same error](https://win-builder.r-project.org/Mwk3Qd4J3VT8) keeps occurring with the old R. I'm sure it's frustrating to debug remotely. I'll try to install an old version of R on my Windows laptop to figure out what's going on.

**Comment by mebrooks** [comment]
Ugh.  I cannot replicate this error in R 3.5.3 on my Windows laptop.

**Comment by bbolker** [comment]
Are you 100% sure you re-built the tarball before sending to winbuilder?

Cross-linking [the "0.2.4 checklist" issue](https://github.com/glmmTMB/glmmTMB/issues/493#issuecomment-578569564) here; this issue is almost certainly related to the conditional/different exporting of the `Anova` and `effects` methods depending on R version.  I don't know whether it interacts with `car`/`effects` versions or not, and/or the `_R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_` environment variable.

**Comment by bbolker** [comment]
Ugh.  I built the tarball myself to check, and got the same results.

I'm kind of stumped.

I don't know whether it's worse to bail out and condition these tests on `if (getRversion() >= 3.6.0)` or to leave them failing on R 3.5.3 ... I keep going round in circles about why the tests are failing. Thought about putting some debugging code in the examples (which looks like it would get printed in the win-builder log, if it was associated with a failing test or example), but I can't quite decide what to do.  It feels like `trace()` is appropriate to see which methods are being used, but I can't even figure out how it works locally, let alone hoping that it does something sensible on the remote platform.

Another option is to cry for help on `r-package-devel@r-project.org` ...

**Comment by bbolker** [comment]
Where are we on this?  If you want I can implement the brute force `if (getRversion() >= "3.6.0"` approach tomorrow ...

**Comment by mebrooks** [comment]
I emailed the [devel list](https://stat.ethz.ch/pipermail/r-package-devel/2020q1/004945.html) but haven't gotten any reply. Did I ask in the wrong way somehow? I'm in favor of the brute force approach you suggest.

**Comment by bbolker** [comment]
I think you may have left out some details (i.e. I think this must have to do with the changes in R controlling which S3 methods are loaded/searched for where, and `_R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_` (enabled in R [here](https://github.com/wch/r-source/commit/753ceaea9854d0b4d7a363041f0176ecc1b036fb): I have so far been able to find very little documentation on this change.

**Comment by mebrooks** [comment]
I built it and tested on my computer and all win-builder versions. They were all fine [except R 3.5.3](https://win-builder.r-project.org/QZwi01oZFYs1/00check.log).
```
== Failed ======================================================================
  -- 1. Error: (unknown) (@test-downstream.R#57)  --------------------------------
  object 'fmd' not found
  Backtrace:
   1. stats::model.frame(fmd) test-downstream.R:57:0
  ```

I think these lines may also need to get protected by the if-statement
```
model.frame(fmd)
model.matrix(fmd)
```

**Comment by bbolker** [comment]
Sorry about that, I'm getting sloppy.

**Comment by mebrooks** [comment]
Now there's only a [warning on R 3.5.3](https://win-builder.r-project.org/rHWX66F4jXvL). I think that should be ok.
```
* checking re-building of vignette outputs ... [160s] WARNING
Error in re-building vignettes:
  ...
Loading required package: stats4
Warning in qt((1 - level)/2, df) : NaNs produced
Loading required package: carData
```

**Comment by bbolker** [comment]
Ugh, that WARNING is actually referring to this, from later on:

```
Quitting from lines 170-176 (model_evaluation.Rnw) 
Error: processing vignette 'model_evaluation.Rnw' failed with diagnostics:
subscript out of bounds
Execution halted
```

**Pull request merged**
